# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url:
date_format: "ordinal"
title: viakiba
subtitle: "viakiba"
description: "viakiba的个人博客"
keywords: viakiba
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: viakiba
organization: kaixin001.com
organization_url: http://www.kaixin001.com
github_username: viakiba
location: BeiJing, China
email: viakiba@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 我的首页

  -
    href: /categories/
    label: 博客分类

  -
    href: /archives/
    label: 归档

  -
    # href: /apiservice/
    # label: 资源

  -
    href: /toollink/
    label: 链接

  -
    # href: /links/
    # label: 技术友链

  # -
  #   href: /vita/
  #   label: 一些资源

  -
    href: /about/
    label: viakiba


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: viakiba/viakiba.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: viakiba
    repo: viakiba.github.io
    oauth:
        client_id: 65bd59956f0bd66671f4
        client_secret: 699e08cb16bc11e9c07fb451d058f852144f22a0
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: viakiba
    repo: viakiba.github.io
    clientID: 65bd59956f0bd66671f4
    clientSecret: 699e08cb16bc11e9c07fb451d058f852144f22a0
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-121702599-1
